version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: car-visits-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/imports:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=car-visits
        - MYSQL_USER=mysqluser
        - MYSQL_PASSWORD=secret
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      container_name: car-visits-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: car-visits-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

